version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  registry:
    image: registry:2
    restart: always
    volumes:
      - registry:/var/lib/registry
    environment:
      - VIRTUAL_HOST=rscdev.azurecr.io
      - VIRTUAL_PORT=5000

  helm:
    build:
      context: ./
    restart: always
    volumes:
      - helm:/root/.helm/repository/local
    environment:
      - VIRTUAL_HOST=charts.stage.rsc7.com
      - VIRTUAL_PORT=8879

volumes:
  registry:
    external: true
  helm:
    external: true
