version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  registry:
    image: registry:2
    restart: always
    volumes:
      - registry:/var/lib/registry
    environment:
      - VIRTUAL_HOST=rscdev.azurecr.io
      - VIRTUAL_PORT=50000

  helm:
    build:
      context: .
    restart: always
    environment:
      - VIRTUAL_HOST=charts.stage.rsc7.com
      - VIRTUAL_PORT=8879
